  redis:
    image: redis
    volumes:
      - ./data:/data/
    ports:
      - "6379:6379"

  acs:
    build: .
    links:
      - redis
    volumes:
      - .:/app/
    ports:
      - 8484:8484
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8484
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
